### ISSUE TITLE
"/" 페이지에서 많은 req 요청 이슈

### ISSUE THREAD

**Issue by 0gunkim** [Yang-ah/select_movie#18]
## 이슈내용

"/" 에서 detail에 대한 많은 요청이 되고 있습니다. 

<img width="615" alt="스크린샷 2023-08-18 오후 2 29 48" src="https://github.com/Yang-ah/select_movie/assets/116594422/e6e78cb3-f119-42c7-880d-c76e71e8a317">
<img width="373" alt="스크린샷 2023-08-18 오후 2 30 56" src="https://github.com/Yang-ah/select_movie/assets/116594422/e9075d15-5f32-4dcc-8f35-70277cf1ad22">

## 이해과정

"/detail" api가 "/"에서 요청이 되고있습니다. 

일단 사용되는 코드를 보니 로그인 상태에 따라서 isLiked가 업데이트가 되고있습니다.
isLiked는 UI에서 ```{isLiked ? <SolidHeartIcon /> : <HeartIcon />}``` 활용 되고있습니다. 
메인페이지에 대한 api 에서 isLike값이 있는지 명세서가 없어서 확인을 못했지만 개발당시  isLike값이 없어서 detail api를 활용했을 거라고 생각했습니다. 
일단 불필요한 요청이 많기 때문에 주석처리 하겠습니다.  isLike에 따라서 변경되는 UI는 리뷰듣고 개선하면 좋을 것 같습니다.

위 내용에 대한 코드
/posterHome
```typescript
  const fetchMovieData = async () => {
    const response = await getMovie(movie.id);
    console.log(response);
    if (isLogin) {
      setIsLiked(response.data.isLiked);
    } else {
      setIsLiked(false);
    }
  };

```

## 해결(임시)

2600 요청에서 160으로 줄었습니다.
이미지 요청에 대한 이슈를 이야기 해보고 isLike값으로 사용되는 좋아요 버튼도 같이 개선하면 좋을 것 같습니다.

<img width="369" alt="스크린샷 2023-08-18 오후 2 44 58" src="https://github.com/Yang-ah/select_movie/assets/116594422/b4217fcb-f201-40a1-a767-a2703d6480c2">

**Comment by Yang-ah** [comment]
## IsLiked 관련 이슈

기재해주신 이슈 확인하였습니다 :)
Home("/")에서 사용중인 api( `/movies/top`, `/movies/{id}/detail`)에서 isLiked 접근 가능합니다.
현재 detail을 추가로 요청할 필요가 없음에도 요청하고 있고, 0gumkim님의 말씀이 맞습니다. 
 
현재 리팩토링 진행중에 있고, `refactor` 브랜치로 머지 요청 주신 Pull Request 수락하겠습니다. 
swagger UI 링크 별도로 안내드리겠습니다 :)

**Comment by 0gunkim** [comment]
확인했습니다
