### ISSUE TITLE
[TODO] "/"

### ISSUE THREAD

**Issue by 0gunkim** [Yang-ah/select_movie#20]
## 메인 페이지에서  detail API사용하지 않고 좋아요 버튼 개선하기
- [x] #18 
- [x] API변경 및 좋아요 버튼 UI 되돌리기
- [x] merge #22 
## 이미지 요청 줄이기
- [x] 리뷰 듣기
- [x] 개선하기 

<img width="298" alt="스크린샷 2023-08-18 오후 2 53 40" src="https://github.com/Yang-ah/select_movie/assets/116594422/6eeac8d0-b642-43ff-ad22-9dbf97ecc7e4">
<img width="611" alt="스크린샷 2023-08-18 오후 1 57 56" src="https://github.com/Yang-ah/select_movie/assets/116594422/9455762e-e45f-4531-8432-f889513eec57">

**Comment by Yang-ah** [comment]
확인했습니다 :) 감사합니다 !
