### ISSUE TITLE
Error: Home 접속 시 발생하는 API 요청 에러

### ISSUE THREAD

**Issue by Yang-ah** [Yang-ah/select_movie#21]
- [x] 에러 발생 원인 찾기 
- [x] 에러 핸들링

<img width="475" alt="스크린샷 2023-08-19 15 14 53" src="https://github.com/Yang-ah/select_movie/assets/97151214/cbd77cfe-6697-4694-945e-b5bceb7c7270">

**Comment by 0gunkim** [comment]
"users/me" API호출에서 이슈가 발생한 것 같습니다.
custom hook으로 분리하셔서 사용 중이고, 스웨거로 실행 결과로 토큰이 필요한 API인데 로그인 하지 않은(토큰이 없는) 상태에서 useMe 커스텀훅 안에있는 useEffect가 작동하여 발생하는 이슈네요 (주석처리 했을 때 unauthorized 없어짐)
<img width="436" alt="스크린샷 2023-08-19 오후 3 54 13" src="https://github.com/Yang-ah/select_movie/assets/116594422/938f6ffc-a7e5-4a9e-b164-dae02a76c88b">
